export type dataGrid={
    id:number,
    name:string,
    username:string,
    email:string,
    phone:string,
    website:string,
    company:{
        name:string,
        bs:string,
        catchPhrase:string,
    },
    address:{
        city:string,
        street:string,
        suite:string,
        zipcode:string
    }
}